version: '3.8'

services:
  nginx:
    image: meu-nginx:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - 80:80
    # volumes:
    #   - ./static:/usr/share/nginx/html

  db:
    image: postgres:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Dahh7deiKeexiep4
      - POSTGRES_DB=mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

# volumes:
#   static:
